// packages/demo-react/src/pages/Popup.tsx
import { useEffect } from 'react';
import './Popup.css';

export default function() {
  useEffect(() => {
    console.log("Hello from the popup!");
  }, []);

  return (
    <div>
      <img src="/icon-with-shadow.svg" />
      <h1>vite-plugin-web-extension</h1>
      <p>
        Template: <code>react-ts</code>
      </p>
    </div>
  )
}

// packages/create-vite-plugin-web-extension/templates/vue-js/src/pages/Popup.vue
<script setup>
console.log("Hello from the popup!");
</script>

<template>
  <div>
    <img src="../../public/icon-with-shadow.svg" />
    <h1>vite-plugin-web-extension</h1>
    <p>Template: ${{ template.templateName }}</p>
  </div>
</template>

<style>
html,
body {
  width: 300px;
  height: 400px;
  padding: 0;
  margin: 0;
}

body {
  background-color: rgb(36, 36, 36);
}

body > div {
  height: 100%;
  display: flex;
  flex-direction: column;
  gap: 16px;
  align-items: center;
  justify-content: center;
}

img {
  width: 200px;
  height: 200px;
}

h1 {
  font-size: 18px;
  color: white;
  font-weight: bold;
  margin: 0;
}

p {
  color: white;
  opacity: 0.7;
  margin: 0;
}
</style>
